[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hello_world = "AYy6VYeespnPnVb6c7sbkdX1irZ5vQxgRtpbCUjJx9mr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/miquel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
